In [21]:
#Create a null vector of size 10 but the fifth value which is 1.

import numpy as np
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [22]:
#2. Create a vector with values ranging from 10 to 49.
import numpy as np
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [23]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8

import numpy as np
z = np.arange(9).reshape(3,3)
print(z)

        

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [24]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np
l = [1,2,0,0,4,0]
z = np.array(l)
l_new = list(np.nonzero(z)[0])
print(l_new)

[0, 1, 4]


In [26]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.
import numpy as np 
u = np.random.random((10,10))
print(u)
umin,umax = u.min(),u.max()
print("minimum and maximum values:")
print(umin,umax)

[[0.31588732 0.79605779 0.48409834 0.4079178  0.55048683 0.34782106
  0.90698011 0.93906671 0.77127654 0.40074276]
 [0.92915159 0.57086091 0.62164298 0.25933821 0.36205434 0.2479902
  0.01218251 0.6345124  0.9310603  0.50546726]
 [0.9220527  0.51649521 0.48478434 0.94580416 0.37887756 0.81314126
  0.54811375 0.95789746 0.47936866 0.60568983]
 [0.1781726  0.37716712 0.64859658 0.9072112  0.42186883 0.00191074
  0.13004852 0.8156539  0.29317824 0.03309841]
 [0.58659076 0.96493712 0.34992318 0.43067842 0.3673997  0.82154616
  0.76211142 0.5259477  0.82097217 0.89150747]
 [0.74562399 0.84495953 0.95488749 0.20128549 0.24225816 0.41693327
  0.04519045 0.2200011  0.4662236  0.95619797]
 [0.82219581 0.94035893 0.36530868 0.01045143 0.95337597 0.03413072
  0.83090388 0.98525467 0.02139596 0.31085158]
 [0.77573949 0.83400348 0.86464745 0.1703996  0.04198138 0.35689969
  0.9133461  0.84527054 0.52126961 0.57544772]
 [0.31433519 0.63951973 0.55178349 0.65157521 0.51661919 0.30813833
  0.97193572 

In [27]:
# 6. Create a random vector of size 30 and find the mean value.

z = np.random.random(30)
m =z.mean()
print(m)

0.4381379424029304
